create table if not exists public.media (

  id bigint
    generated by default as identity
    primary key,

  filename text not null,

  storage_path text not null
    unique,

  description text
    default '',

  details text
    default '',

  media_type text not null,

  created_at timestamptz
    not null
    default now()

);